<?php

namespace app\controllers;

use Yii;
use Yii\helpers\ArrayHelper;
use app\models\AccessToken;
use yii\rest\ActiveController;
// use yii\filters\auth\HttpBearerAuth; // new add
use app\models\LoginForm; //new add
use yii\filters\auth\QueryParamAuth; //new add
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 *
 * @property-read AccessToken|null $accessToken
 *
 */

class AccessTokenController extends ActiveController
{
    public $modelClass = 'app\models\AccessToken';

    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        return $action;
    }

    public function actionCreate() //POST
    {
        $request = Yii::$app->request;
        $post = $request->post();
        return AccessToken::find()->where($post)->all();
    }

    public function actionIndex() //GET
    {
        // $LoginForm = new LoginForm(); //
        // return $LoginForm->getGardener(); //
        return AccessToken::find()->all();

        //參考語法:
        // $titles = Yii::$app->db->createCommand('SELECT * FROM gardener WHERE gardener_id = 23')
        //     ->queryOne();
        // return $titles;

        //參考語法:
        //return Article::find()->where(['like','title', $_POST['keyword']])->all();

        // return $this->render('id');
        // $Gardeners = Gardener::find()->orderBy('id')->all();
        // return $Gardeners;
    }

    public function actionSendEmail()  //假如是get请求
    {
        $rsp = new \stdClass();
        $rsp->msg = "FFFF";
        return $rsp;
    } //

    public function actionSendUser()  //假如是get请求
    {
        // $rsp = new \stdClass();
        // $rsp->msg ="AAA";
        $rsp = $_GET['id'];
        return AccessToken::findAll($rsp);
    }

    public function init()
    {
        parent::init();
        Yii::$app->user->enableSession = false;
    }
    
    public function actionQqq()  //假如是get请求
    {
        return "BBQBBQBBQBBQBBQBBQBBQ";
    } //
}