<?php

namespace app\controllers;

use Yii;
use yii\base\Model;
use app\models\Gardener;
use app\models\Chatdata;
// use app\models\Chatpartnerlist;
use app\models\Chatrecord;
use yii\filters\AccessRule;
// use yii\rest\ActiveController;
use app\controllers\BaseController; //改用BaseController，因為他已經繼承ActiveController

class ChatController extends BaseController
{
    public $modelClass = 'app\models\Chat';

    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        return $action;
    }

    public function actionCreate() //POST
    {
        $request = Yii::$app->request;
        $post = $request->post();
        return Gardener::find()->where($post)->all();
    }

    public function actionIndex() //GET
    {
        return Gardener::find()->all();
    }

    public function init()
    {
        parent::init();
        Yii::$app->user->enableSession = false;
    }

    public function actionSendMessage() // Post 新增一筆聊天紀錄
    {
        $user = Yii::$app->user->identity;
        $chat_data = new Chatdata();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组

        // 傳送方帳號
        $sender_id = $user->gardener_id;
        $chat_data->sender_id = $sender_id;

        // 接收方帳號
        $receiver_account = $post['other_account'];
        $chat_data->receiver_account = $receiver_account;

        // 訊息內容(或圖片)
        $send_message = $post['chat_data'];
        $chat_data->chat_data = $send_message;

        return [
            $chat_data->generateChatdata()
        ];
    }

    public function actionRecord() // Post 查詢所有聊天紀錄
    {
        $user = Yii::$app->user->identity;
        $chat_record = new Chatdata();


        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组


        // 傳送方
        $sender_id = $user->gardener_id;
        $chat_record->sender_id = $sender_id;


        // 接收方帳號
        $receiver_account = $post['other_account'];
        $chat_record->receiver_account = $receiver_account;


        return
            $chat_record->Chatrecord();
    }
}