<?php
//登入註冊少給東西的話，不會跳出少打東西，只會說執行不動///////////

namespace app\controllers;

use Yii;
use Yii\helpers\ArrayHelper;
use app\models\AccessToken;
use app\models\Gardenerofleaf;
use yii\rest\ActiveController;
// use yii\filters\auth\HttpBearerAuth; // new add
use app\models\LoginForm; //new add
use yii\filters\auth\QueryParamAuth; //new add
use yii\base\Model;
use yii\filters\AccessRule;
use yii\web\UploadedFile;

/**
 * LoginForm is the model behind the login form.
 *
 * @property-read Gardenerofleaf|null $gardenerofleaf
 *
 */

class GardenerofleafController extends BaseController
{
    public $modelClass = 'app\models\Gardenerofleaf';

    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        return $action;
    }

    public function actionCreate() //POST
    {
        $request = Yii::$app->request;
        $post = $request->post();
        return Gardenerofleaf::find()->where($post)->all();
    }
    public function actionIndex() //GET
    {
        return Gardenerofleaf::find()->all();
    }
    public function init()
    {
        parent::init();
        Yii::$app->user->enableSession = false;
    }
    public function beforeAction($action)
    {
        if ($action->id === 'find-all-gardener-of-leaf') {
            $this->enableCsrfValidation = false; // 可选：如果登录不需要 CSRF 验证，可以禁用
            $this->detachBehavior('authenticator'); // 解除认证行为
        }
        return parent::beforeAction($action);
    }

    public function actionFindAllGardenerOfLeaf()
    {
        $gardener_of_leaf = new Gardenerofleaf();

        $post = file_get_contents('php://input');//获取请求体
        $post =  json_decode($post, true);//解析成数组

        $leaf_id = $post['leaf_id'];
        $gardener_of_leaf->leaf_id = $leaf_id;
        
        return $gardener_of_leaf->getAllGardener();
    }

    public function actionAddGardener() //Post  葉子多一位園丁
    {
        $user = Yii::$app->user->identity;
        $gardener_of_leaf = new Gardenerofleaf();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组
        // gardener_id
        $gardener_of_leaf->gardener_id = $user->gardener_id;
        // leaf_id
        $leaf_id = $post['uuid'];
        $gardener_of_leaf->leaf_id = $leaf_id;
        return [
            $gardener_of_leaf->generateOneGardener()
        ];
    }

    public function actionDeleteGardener()
    {
        $user = Yii::$app->user->identity;
        $gardener_of_leaf = new Gardenerofleaf();

        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组
        // gardener_id
        $gardener_of_leaf->gardener_id = $user->gardener_id;
        // leaf_id
        $leaf_id = $post['uuid'];
        $gardener_of_leaf->leaf_id = $leaf_id;

        return [
            $gardener_of_leaf->deleteGardener()
        ];
    }
    public function actionAddPptFile()
    {
        $user = Yii::$app->user->identity;
        $gardener_of_leaf = new Gardenerofleaf();

        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        $gardener_of_leaf->gardener_id = $user->gardener_id;

        $leaf_id = $post['uuid'];
        $gardener_of_leaf->leaf_id = $leaf_id;

        // 1表示file
        return [
            $gardener_of_leaf->addPpt(1)
        ];
    }
    public function actionAddPptData()
    {
        $user = Yii::$app->user->identity;
        $gardener_of_leaf = new Gardenerofleaf();

        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        $gardener_of_leaf->gardener_id = $user->gardener_id;

        $leaf_id = $post['uuid'];
        $gardener_of_leaf->leaf_id = $leaf_id;

        // 0表示data
        return [
            $gardener_of_leaf->addPpt(0)
        ];
    }

    public function actionUpdatePpt()
    {
        $user = Yii::$app->user->identity;
        $gardener_of_leaf = new Gardenerofleaf();

        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        // gardener_id
        $gardener_of_leaf->gardener_id = $user->gardener_id;
        // leaf_id
        $leaf_id = Yii::$app->request->post('uuid');
        $gardener_of_leaf->leaf_id = $leaf_id;
        // file
        $gardener_of_leaf->file = UploadedFile::getInstanceByName('file');
        if ($gardener_of_leaf->file === null) {
            return [[
                "error_message" => "檔案為空",
            ]];
        } else {
            return [$gardener_of_leaf->UpdatePPT()];
        }
    }
}