<?php
//登入註冊少給東西的話，不會跳出少打東西，只會說執行不動///////////

namespace app\controllers;

use Yii;
use Yii\helpers\ArrayHelper;
use app\models\Gardener;
use app\models\AccessToken;
// use yii\rest\ActiveController;   
use app\controllers\BaseController; //改用BaseController，因為他已經繼承ActiveController
use GuzzleHttp\Client;
// use yii\filters\auth\HttpBearerAuth; // new add
use app\models\LoginForm; //new add
use yii\filters\auth\QueryParamAuth; //new add
use yii\base\Model;
use yii\filters\AccessRule;
use yii\web\UploadedFile;

/**
 * LoginForm is the model behind the login form.
 *
 * @property-read Gardener|null $gardener
 * 
 */

class GardenerController extends BaseController
{
    public $modelClass = 'app\models\Gardener';

    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        return $action;
    }

    public function actionCreate() //POST
    {
        $request = Yii::$app->request;
        $post = $request->post();
        return Gardener::find()->where($post)->all();
    }
    public function actionIndex() //GET
    {
        $result = Yii::$app->db->createCommand('SELECT * FROM gardener')->queryAll();
        return $result;

        //參考語法:
        //return Article::find()->where(['like','title', $_POST['keyword']])->all();

        // return $this->render('id');
        // $Gardeners = Gardener::find()->orderBy('id')->all();
        // return $Gardeners;
    }
    public function init()
    {
        // parent::init();
        // Yii::$app->user->enableSession = false;
    }

    public function beforeAction($action)
    {
        if ($action->id === 'index' or $action->id === 'login' or $action->id === 'signup-test') {
            $this->enableCsrfValidation = false; // 可选：如果登录不需要 CSRF 验证，可以禁用
            $this->detachBehavior('authenticator'); // 解除认证行为
        }
        return parent::beforeAction($action);
    }

    public function actionInfo() // Post
    {
        $Gardeners = new Gardener();

        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        $gardener_firstname = Yii::$app->request->post('gardener_firstname');
        $Gardeners->gardener_firstname = $gardener_firstname;

        $Gardeners->file = UploadedFile::getInstanceByName('file');
        if ($Gardeners->file === null) {
            return [[
                "error_message" => "檔案為空",
            ]];
        } else {
            return [
                $Gardeners->gardenerInfo()
            ];
        }
    }

    public function actionSignupTest() // new add //註冊 //Post
    {
        $Gardeners = new Gardener();

        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        $account = Yii::$app->request->post('account');
        $password = Yii::$app->request->post('password');
        $first_name = Yii::$app->request->post('first_name');
        //$id = $Gardeners->findByAccount($account);

        $Gardeners->account = $account;
        $Gardeners->password1 = $password;
        $Gardeners->first_name = $first_name;

        // 上传文件接收
        $Gardeners->file = UploadedFile::getInstanceByName('file');
        if ($Gardeners->file === null) {
            return [[
                "error_message" => "檔案為空",
            ]];
        } else {
            return [
                $Gardeners->signup()
            ];
        }
    }
    /**
     * LoginForm is the model behind the login form.
     *
     * @property-read Gardener|null $gardener
     *
     */

    /**
     * 登录
     */
    public function actionLogin() //POST
    {
        $LoginForm = new LoginForm();

        $gardener_id = 0; //初始化設置0
        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        // $account = 'TEST';
        // $password = 'TEST';

        $account = $post['account'];
        $password = $post['password'];
        $LoginForm->account = $account;
        $LoginForm->password = $password;

        if ($LoginForm->load(Yii::$app->getRequest()->getBodyParams(), '')) {
            return [
                $LoginForm->login(),
            ];
        } else {
            return 'error';
            // return $LoginForm->getFirstErrors();
        }
    }

    public function actionLogout() //POST   
    {
        $user = Yii::$app->user->identity;
        // return $user->gardener_id;//回傳的53是access token對應的gardener_id來的

        $gardener = new Gardener();

        $gardener_id = 0; //初始化設置0  
        // $post = file_get_contents('php://input'); //获取请求体   
        // $post =  json_decode($post, true); //解析成数组  

        // $account = $post['account'];
        // return $user->account;
        $gardener->gardener_id1 = $user->gardener_id;
        // return $gardener->gardener_id1;
        // $gardener_id = $gardener->findByAccount($account)->gardener_id;

        //如果$gardener_id不存在
        // if ($gardener_id == null) {
        //     return [[
        //         'error_message' => "account不存在",
        //     ]];
        // }
        // //如果access token的id和account對應的id相匹配
        // else if ($user->gardener_id == $gardener_id) {
        return [
            $gardener->logout(),
        ];
        // } else {
        //     return [[
        //         'error_message' => "你給的access token跟account不匹配",
        //     ]];
        // }
    }

    public function actionEdit() //POST
    {
        $user = Yii::$app->user->identity;

        $gardener = new Gardener();

        // $gardener_id = 0; //初始化設置0
        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        $password = $post['password'];
        $first_name = $post['first_name'];

        $gardener->gardener_id1 = $user->gardener_id;

        $gardener->password1 = $password;
        $gardener->first_name = $first_name;

        return [
            $gardener->edit(),
        ];
    }

    public function actionEditAvatar() // Post
    {
        $user = Yii::$app->user->identity;

        $gardener = new Gardener();

        $gardener->gardener_id1 = $user->gardener_id;

        $gardener->file = UploadedFile::getInstanceByName('file');
        if ($gardener->file === null) {
            return [[
                "error_message" => "檔案為空",
            ]];
        } else {
            return [
                $gardener->EditAvatar()
            ];
        }
    }

    public function actionQqq()  //假如是post请求
    {
    } //

    public function actionSearch()
    {
        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        $enter_firstname = $post['enter_firstname'];

        $gardener = new Gardener();
        $gardener->gardener_firstname = $enter_firstname;

        return $gardener->search();
    }

    public function actionShowInfo() // 回傳某園丁所有詳細資訊(透過account)(不含頭像)
    {
        $user = Yii::$app->user->identity;

        $gardener = new Gardener();

        $gardener->gardener_id1 = $user->gardener_id;

        return [
            $gardener->ShowInfo()
        ];
    }

    public function actionShowInfoAvatar() // 回傳某園丁所有詳細資訊(透過account)(只有頭像)
    {
        $user = Yii::$app->user->identity;

        $gardener = new Gardener();

        $gardener->gardener_id1 = $user->gardener_id;

        return [
            $gardener->ShowInfoAvatar()
        ];
    }
    
    public function actionGetOtherAvatar(){
        $gardener = new Gardener();

        $post = file_get_contents('php://input'); //获取请求体
        $post =  json_decode($post, true); //解析成数组

        $account = $post['account'];

        $gardener->account1 = $account;

        return [
            $gardener->GetOtherAvatar()
        ];
    }
}