<?php

namespace app\controllers;

use Yii;
use yii\base\Model;
use app\models\Gardener;
use app\models\Leaf;
use app\models\Normalleaf;
use app\models\Managerofleaf;
use app\models\Gardenerofleaf;
use app\models\Reportrecord;
use app\models\Chatdata;
use app\models\Chatpartnerlist;
use app\models\Chatrecord;
use app\models\Plantofgardener;
use app\models\Fileofplant;
use yii\filters\AccessRule;
use yii\rest\ActiveController;


class PlantController extends BaseController
{
    public $modelClass = 'app\models\Plant';

    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        return $action;
    }

    public function actionCreate() //POST
    {
        $request = Yii::$app->request;
        $post = $request->post();
        return Gardener::find()->where($post)->all();
    }

    public function actionIndex() //GET
    {
        return Gardener::find()->all();
    }

    public function init()
    {
        parent::init();
        Yii::$app->user->enableSession = false;
    }

    public function actionCreatePlant()
    {
        $user = Yii::$app->user->identity;
        $create_plant = new PlantOfGardener();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组

        // 園丁id
        $create_plant->gardener_id = $user->gardener_id;

        // Plant的名字
        $plant_name = $post['plant_name'];
        $create_plant->plant_name = $plant_name;

        // 花樹種類
        $plant_type = $post['plant_type'];
        $create_plant->plant_type = $plant_type;

        return [
            $create_plant->generatePlant()
        ];
    }

    public function actionShowAllPlants()
    {
        $user = Yii::$app->user->identity;
        $all_plant = new PlantOfGardener();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组

        // 園丁id
        $all_plant->gardener_id = $user->gardener_id;
        return [
            $all_plant->returnAllPlant()
        ];
    }

    public function actionShowFile()
    {
        $user = Yii::$app->user->identity;
        $fileOfPlant = new FileOfPlant();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组

        // gardener_id
        $fileOfPlant->gardener_id = $user->gardener_id;
        // plant_name
        $plant_name = $post['plant_name'];
        $fileOfPlant->plant_name = $plant_name;
        // fruit_num
        $fruit_num = $post['fruit_num'];
        $fileOfPlant->fruit_num = $fruit_num;

        return $fileOfPlant->returnAllFile();
    }

    public function actionShowFruitInfo()
    {
        $user = Yii::$app->user->identity;
        $fileOfPlant = new FileOfPlant();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组

        // gardener_id
        $fileOfPlant->gardener_id = $user->gardener_id;
        // plant_name
        $plant_name = $post['plant_name'];
        $fileOfPlant->plant_name = $plant_name;

        return $fileOfPlant->showFruitInfo();
    }

    public function actionShowPlantPicture()
    {
        $user = Yii::$app->user->identity;
        $fileOfPlant = new FileOfPlant();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组

        // gardener_id
        $fileOfPlant->gardener_id = $user->gardener_id;
        // plant_name
        $plant_name = $post['plant_name'];
        $fileOfPlant->plant_name = $plant_name;

        return $fileOfPlant->showPlantPicture();
    }

    public function actionShowRiv()
    {
        $user = Yii::$app->user->identity;
        $fileOfPlant = new FileOfPlant();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组

        // gardener_id
        $fileOfPlant->gardener_id = $user->gardener_id;
        // plant_name
        $plant_name = $post['plant_name'];
        $fileOfPlant->plant_name = $plant_name;

        return $fileOfPlant->showRiv();
    }

    public function actionHarvestFruit()
    {
        $user = Yii::$app->user->identity;
        $gardenerOfLeaf = new Gardenerofleaf();
        $fileOfPlant = new FileOfPlant();

        $post = file_get_contents('php://input'); //获取请求体
        $post = json_decode($post, true); //解析成数组

        // gardener_id
        $fileOfPlant->gardener_id = $user->gardener_id;
        $gardenerOfLeaf->gardener_id = $user->gardener_id;

        // file_name
        $file_name = $post['file_name'];
        $fileOfPlant->file_name = $file_name;

        // 先去gardener of leaf裡抓路徑、檔名，再傳到 fileOfPlant 的 findFileOfLeafInfo()
        $leaf_id = $post['uuid'];
        $gardenerOfLeaf->leaf_id = $leaf_id;
        $fileOfPlant->leaf_id = $leaf_id;
        // return [
        //     $gardenerOfLeaf->findFileOfLeafInfo()
        // ];
        $gardener_file_name = $gardenerOfLeaf->findFileOfLeafInfo()['gardener_file_name'];
        // return $gardener_file_name;

        if ($gardener_file_name != null) {
            if ($gardener_file_name == false) {
                return [[
                    'error_message' => "UUID not found!"
                ]];
            }
            $gardener_file_path = $gardenerOfLeaf->findFileOfLeafInfo()['gardener_file_path'];
            $fileOfPlant->fileName = $gardener_file_name;
            $fileOfPlant->filePath = $gardener_file_path;

            $plant_name = $post['plant_name'];
            $fileOfPlant->plant_name = $plant_name;

            return [
                $fileOfPlant->addOneFile()
            ];
        } else {
            return [[
                'error_message' => "Gardener is not in the leaf!"
            ]];
        }
    }
}
